# Generated by Django 6.0.5 on 2026-05-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('anotaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('dia_completo', 'Día completo'), ('franja', 'Franja horaria')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, help_text='Solo para rangos de días completos', null=True)),
                ('hora_inicio', models.TimeField(blank=True, help_text='Solo para franjas horarias', null=True)),
                ('hora_fin', models.TimeField(blank=True, help_text='Solo para franjas horarias', null=True)),
                ('recurrencia', models.CharField(choices=[('ninguna', 'Sin recurrencia'), ('diaria', 'Diaria'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], default='ninguna', max_length=20)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('capacidad_maxima', models.PositiveIntegerField(blank=True, help_text='Máximo de citas permitidas en esa franja. Vacío = bloqueado total.', null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuración de calendario',
                'verbose_name_plural': 'Configuraciones de calendario',
                'ordering': ['fecha_inicio', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion_estimada', models.DurationField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
