# Generated by Django 6.0.5 on 2026-05-22 01:47

import apps.agenda.models.configuracion_calendario
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_configuracion_fecha_inicio_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracioncalendario',
            name='dias_laborales',
            field=models.JSONField(blank=True, default=apps.agenda.models.configuracion_calendario.default_dias_laborales, help_text='Dias laborales (0=Lunes, 6=Domingo)', null=True),
        ),
    ]
