# Generated by Django 6.0.5 on 2026-05-14 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0002_initial'),
        ('taller', '0001_initial'),
        ('vehiculos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenservicio',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_servicio', to='vehiculos.estado'),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_servicio', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordenserviciodetalle',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_detalle', to='taller.ordenservicio'),
        ),
        migrations.AddField(
            model_name='ordenserviciodetalle',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_detalle', to='agenda.servicio'),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='cita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recepciones', to='agenda.cita'),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepciones', to='vehiculos.vehiculo'),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='recepcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_servicio', to='taller.recepcion'),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='recepcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidencias', to='taller.recepcion'),
        ),
    ]
