# Generated by Django 6.0.3 on 2026-04-27 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permiso',
            old_name='permiso',
            new_name='accion',
        ),
        migrations.AlterUniqueTogether(
            name='permiso',
            unique_together={('modulo', 'accion')},
        ),
    ]
