# Generated by Django 6.0.3 on 2026-03-12 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('url_archivo', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('recepcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidencias', to='administracion.recepcion')),
            ],
        ),
    ]
