# Generated by Django 6.0.3 on 2026-03-13 04:27

import cloudinary.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_evidencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencia',
            name='fecha_subida',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evidencia',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='evidencia',
            name='tipo',
            field=models.CharField(choices=[('foto', 'Foto'), ('video', 'Video')], max_length=10),
        ),
        migrations.AlterField(
            model_name='evidencia',
            name='url_archivo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='archivo'),
        ),
    ]
