# Generated by Django 6.0.3 on 2026-04-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_rename_permiso_permiso_accion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('dia_completo', 'Día completo'), ('franja', 'Franja horaria')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, help_text='Solo para rangos de días completos', null=True)),
                ('hora_inicio', models.TimeField(blank=True, help_text='Solo para franjas horarias', null=True)),
                ('hora_fin', models.TimeField(blank=True, help_text='Solo para franjas horarias', null=True)),
                ('recurrencia', models.CharField(choices=[('ninguna', 'Sin recurrencia'), ('diaria', 'Diaria'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], default='ninguna', max_length=20)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('capacidad_maxima', models.PositiveIntegerField(blank=True, help_text='Máximo de citas permitidas en esa franja. Vacío = bloqueado total.', null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bloqueo de calendario',
                'verbose_name_plural': 'Bloqueos de calendario',
                'ordering': ['fecha_inicio', 'hora_inicio'],
            },
        ),
    ]
