# Generated by Django 6.0.3 on 2026-03-19

import django.db.models.deletion
from django.db import migrations, models


def migrar_estado_texto_a_fk(apps, schema_editor):
    Orden = apps.get_model('administracion', 'Orden')
    Estado = apps.get_model('administracion', 'Estado')

    for orden in Orden.objects.all():
        nombre_estado = (orden.estado or '').strip()
        if not nombre_estado:
            nombre_estado = 'Pendiente'

        estado, _ = Estado.objects.get_or_create(
            nombre=nombre_estado,
            defaults={
                'descripcion': f'Estado migrado automaticamente desde orden #{orden.id}',
                'is_active': True,
            },
        )
        orden.estado_nuevo_id = estado.id
        orden.save(update_fields=['estado_nuevo'])


def migrar_estado_fk_a_texto(apps, schema_editor):
    Orden = apps.get_model('administracion', 'Orden')

    for orden in Orden.objects.select_related('estado_nuevo').all():
        orden.estado = orden.estado_nuevo.nombre if orden.estado_nuevo_id else 'Pendiente'
        orden.save(update_fields=['estado'])


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='estado_nuevo',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='ordenes_asignadas_tmp',
                to='administracion.estado',
            ),
        ),
        migrations.RunPython(migrar_estado_texto_a_fk, migrar_estado_fk_a_texto),
        migrations.RemoveField(
            model_name='orden',
            name='estado',
        ),
        migrations.RenameField(
            model_name='orden',
            old_name='estado_nuevo',
            new_name='estado',
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='ordenes',
                to='administracion.estado',
            ),
        ),
    ]
