# Generated by Django 6.0.3 on 2026-03-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_orden_estado_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combustible',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
