# Generated by Django 6.0.3 on 2026-03-20 22:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_alter_combustible_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendahorario',
            name='dia_semana',
        ),
        migrations.AddField(
            model_name='agendahorario',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
