# Generated by Django 6.0.3 on 2026-03-20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0007_remove_agendahorario_dia_semana_agendahorario_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendahorario',
            name='dia_semana',
            field=models.CharField(blank=True, choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miercoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sabado'), ('domingo', 'Domingo')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='agendahorario',
            name='fecha',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
