# Generated by Django 6.0.3 on 2026-03-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0008_agendahorario_dia_semana_and_fecha_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendahorario',
            name='tipo_bloque',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('bloqueado', 'Bloqueado')], default='disponible', max_length=20),
        ),
    ]
