# Generated by Django 6.0.3 on 2026-03-20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0009_agendahorario_tipo_bloque'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='mecanico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='citas_asignadas', to='administracion.usuario'),
        ),
    ]
