# Generated by Django 6.0.3 on 2026-03-21 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0010_cita_mecanico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='mecanico',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='cliente',
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='administracion.estado'),
        ),
    ]
