# Generated by Django 6.0.3 on 2026-03-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0011_rename_mecanico_cita_usuario_remove_cita_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoHerramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
