# Generated by Django 6.0.3 on 2026-03-24 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0013_herramienta_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herramienta',
            name='estado',
        ),
    ]
