# Generated by Django 6.0.3 on 2026-03-25 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0014_remove_herramienta_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventarioherramienta',
            name='cantidad_disponible',
        ),
        migrations.RemoveField(
            model_name='inventarioherramienta',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='inventarioherramienta',
            name='ubicacion',
        ),
        migrations.AlterField(
            model_name='inventarioherramienta',
            name='herramienta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.herramienta'),
        ),
    ]
