# Generated by Django 6.0.3 on 2026-03-25 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0015_remove_inventarioherramienta_cantidad_disponible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarioherramienta',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administracion.estadoherramienta'),
            preserve_default=False,
        ),
    ]
